In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.naive_bayes import GaussianNB

In [2]:
df = pd.read_csv("studi_num.csv")
df

JURUSAN  GENDER  ASAL_SEKOLAH  RERATA_SKS  ASISTEN  LAMA_STUDI
0         1       1             1           1        1           1
1         1       1             1           1        1           1
2         1       1             1           1        1           1
3         2       2             1           1        1           1
4         2       2             2           1        1           1
5         2       1             2           1        1           1
6         2       1             1           1        2           2
7         1       1             1           2        1           1
8         1       2             1           2        1           1
9         2       1             1           1        2           2
10        3       1             1           1        1           1
11        2       1             2           2        1           1
12        2       2             1           2        1           2

In [3]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 5].values

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [6]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [8]:
y_pred = model.predict(X_test)
y_pred

array([1, 2, 1, 1])

In [9]:
np.array(y_test)

array([1, 1, 1, 1])

In [11]:
confusion_matrix(y_test, y_pred)

array([[3, 1],
       [0, 0]])

In [12]:
print("Accuracy : ", metrics.accuracy_score(y_test, y_pred))

Accuracy :  0.75


In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.75      0.86         4
           2       0.00      0.00      0.00         0

    accuracy                           0.75         4
   macro avg       0.50      0.38      0.43         4
weighted avg       1.00      0.75      0.86         4



/home/ali-farid/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ali-farid/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ali-farid/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
